version: '3.8'

services:
  db:
    image: postgres:14.1
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  env-stock:
    build: .
    container_name: env-stock
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://root:123456@db:5432/mydatabase
    ports:
      - "8000:8000"

volumes:
  postgres_data: